//
// Created by 19254 on 24-8-26.
//
#include "HYGUI/Text.h"
#include "unordered_map"
#include "tuple"
#include "PrivateDefinition.h"

namespace HYGUI {

const std::unordered_map<char32_t, std::tuple<const char*,const char *>> g_emoji_map = {
  {U'🧌', { "troll","fully-qualified"}},
  {U'🏪', { "convenience store","fully-qualified"}},
  {U'🐪', { "camel","fully-qualified"}},
  {U'🅰', { "A button (blood type)","unqualified"}},
  {U'🥰', { "smiling face with hearts","fully-qualified"}},
  {U'☣', { "biohazard","unqualified"}},
  {U'🏈', { "american football","fully-qualified"}},
  {U'🔬', { "microscope","fully-qualified"}},
  {U'⌛', { "hourglass done","fully-qualified"}},
  {U'⛱', { "umbrella on ground","unqualified"}},
  {U'👦', { "boy","fully-qualified"}},
  {U'🌠', { "shooting star","fully-qualified"}},
  {U'🦭', { "seal","fully-qualified"}},
  {U'🎭', { "performing arts","fully-qualified"}},
  {U'🫀', { "anatomical heart","fully-qualified"}},
  {U'🌻', { "sunflower","fully-qualified"}},
  {U'🧅', { "onion","fully-qualified"}},
  {U'🔚', { "END arrow","fully-qualified"}},
  {U'🍿', { "popcorn","fully-qualified"}},
  {U'🙀', { "weary cat","fully-qualified"}},
  {U'🆖', { "NG button","fully-qualified"}},
  {U'🏴', { "black flag","fully-qualified"}},
  {U'🚠', { "mountain cableway","fully-qualified"}},
  {U'🕢', { "seven-thirty","fully-qualified"}},
  {U'🍺', { "beer mug","fully-qualified"}},
  {U'👵', { "old woman","fully-qualified"}},
  {U'🙂', { "slightly smiling face","fully-qualified"}},
  {U'🎬', { "clapper board","fully-qualified"}},
  {U'💀', { "skull","fully-qualified"}},
  {U'🗯', { "right anger bubble","unqualified"}},
  {U'🏑', { "field hockey","fully-qualified"}},
  {U'🦙', { "llama","fully-qualified"}},
  {U'🕦', { "eleven-thirty","fully-qualified"}},
  {U'😂', { "face with tears of joy","fully-qualified"}},
  {U'🦷', { "tooth","fully-qualified"}},
  {U'🚸', { "children crossing","fully-qualified"}},
  {U'🖊', { "pen","unqualified"}},
  {U'😡', { "enraged face","fully-qualified"}},
  {U'🏟', { "stadium","unqualified"}},
//  {U'9⃣', { "keycap: 9","unqualified"}},
  {U'🎎', { "Japanese dolls","fully-qualified"}},
  {U'🥇', { "1st place medal","fully-qualified"}},
  {U'🫵', { "index pointing at the viewer","fully-qualified"}},
  {U'⏱', { "stopwatch","unqualified"}},
  {U'⚖', { "balance scale","unqualified"}},
  {U'🔡', { "input latin lowercase","fully-qualified"}},
  {U'🎯', { "bullseye","fully-qualified"}},
  {U'🫄', { "pregnant person","fully-qualified"}},
  {U'👌', { "OK hand","fully-qualified"}},
  {U'🐃', { "water buffalo","fully-qualified"}},
  {U'🥓', { "bacon","fully-qualified"}},
  {U'👟', { "running shoe","fully-qualified"}},
  {U'🎰', { "slot machine","fully-qualified"}},
  {U'🧓', { "older person","fully-qualified"}},
  {U'👨', { "man","fully-qualified"}},
  {U'🍂', { "fallen leaf","fully-qualified"}},
  {U'🧿', { "nazar amulet","fully-qualified"}},
  {U'🎿', { "skis","fully-qualified"}},
  {U'🛴', { "kick scooter","fully-qualified"}},
  {U'🦕', { "sauropod","fully-qualified"}},
  {U'🥁', { "drum","fully-qualified"}},
  {U'👖', { "jeans","fully-qualified"}},
  {U'💱', { "currency exchange","fully-qualified"}},
  {U'🔒', { "locked","fully-qualified"}},
  {U'🚂', { "locomotive","fully-qualified"}},
  {U'🧈', { "butter","fully-qualified"}},
  {U'📉', { "chart decreasing","fully-qualified"}},
  {U'🤳', { "selfie","fully-qualified"}},
  {U'🪪', { "identification card","fully-qualified"}},
//  {U'1⃣', { "keycap: 1","unqualified"}},
  {U'🏵', { "rosette","unqualified"}},
  {U'🚪', { "door","fully-qualified"}},
  {U'🥱', { "yawning face","fully-qualified"}},
  {U'🦤', { "dodo","fully-qualified"}},
  {U'🥅', { "goal net","fully-qualified"}},
  {U'🥂', { "clinking glasses","fully-qualified"}},
  {U'🦋', { "butterfly","fully-qualified"}},
  {U'🌋', { "volcano","fully-qualified"}},
  {U'📏', { "straight ruler","fully-qualified"}},
  {U'🤩', { "star-struck","fully-qualified"}},
  {U'🪠', { "plunger","fully-qualified"}},
  {U'🔄', { "counterclockwise arrows button","fully-qualified"}},
  {U'🖖', { "vulcan salute","fully-qualified"}},
  {U'↔', { "left-right arrow","unqualified"}},
  {U'🚆', { "train","fully-qualified"}},
  {U'🌤', { "sun behind small cloud","unqualified"}},
  {U'⚡', { "high voltage","fully-qualified"}},
  {U'🔐', { "locked with key","fully-qualified"}},
  {U'♾', { "infinity","unqualified"}},
  {U'🔶', { "large orange diamond","fully-qualified"}},
  {U'📂', { "open file folder","fully-qualified"}},
  {U'🔜', { "SOON arrow","fully-qualified"}},
  {U'🪂', { "parachute","fully-qualified"}},
//  {U'8⃣', { "keycap: 8","unqualified"}},
  {U'🏳', { "white flag","unqualified"}},
  {U'🟢', { "green circle","fully-qualified"}},
  {U'🛩', { "small airplane","unqualified"}},
  {U'🌖', { "waning gibbous moon","fully-qualified"}},
  {U'🐨', { "koala","fully-qualified"}},
  {U'🍏', { "green apple","fully-qualified"}},
  {U'🟤', { "brown circle","fully-qualified"}},
  {U'📸', { "camera with flash","fully-qualified"}},
  {U'🤼', { "people wrestling","fully-qualified"}},
  {U'🍧', { "shaved ice","fully-qualified"}},
  {U'🏌', { "person golfing","unqualified"}},
  {U'🐚', { "spiral shell","fully-qualified"}},
  {U'😚', { "kissing face with closed eyes","fully-qualified"}},
  {U'😱', { "face screaming in fear","fully-qualified"}},
  {U'❇', { "sparkle","unqualified"}},
  {U'🐐', { "goat","fully-qualified"}},
  {U'📧', { "e-mail","fully-qualified"}},
  {U'🧩', { "puzzle piece","fully-qualified"}},
  {U'👚', { "woman’s clothes","fully-qualified"}},
  {U'😸', { "grinning cat with smiling eyes","fully-qualified"}},
  {U'🪖', { "military helmet","fully-qualified"}},
  {U'🏭', { "factory","fully-qualified"}},
  {U'💌', { "love letter","fully-qualified"}},
  {U'🎴', { "flower playing cards","fully-qualified"}},
  {U'🟡', { "yellow circle","fully-qualified"}},
  {U'🪨', { "rock","fully-qualified"}},
  {U'🎐', { "wind chime","fully-qualified"}},
  {U'💸', { "money with wings","fully-qualified"}},
  {U'🆕', { "NEW button","fully-qualified"}},
  {U'🕤', { "nine-thirty","fully-qualified"}},
  {U'🤿', { "diving mask","fully-qualified"}},
  {U'🦃', { "turkey","fully-qualified"}},
  {U'🔊', { "speaker high volume","fully-qualified"}},
  {U'🖐', { "hand with fingers splayed","unqualified"}},
  {U'🚀', { "rocket","fully-qualified"}},
  {U'🦣', { "mammoth","fully-qualified"}},
  {U'🧘', { "person in lotus position","fully-qualified"}},
  {U'👎', { "thumbs down","fully-qualified"}},
  {U'🦫', { "beaver","fully-qualified"}},
  {U'🖕', { "middle finger","fully-qualified"}},
  {U'🤛', { "left-facing fist","fully-qualified"}},
  {U'🔁', { "repeat button","fully-qualified"}},
  {U'🧥', { "coat","fully-qualified"}},
  {U'🗞', { "rolled-up newspaper","unqualified"}},
  {U'🛹', { "skateboard","fully-qualified"}},
  {U'🥕', { "carrot","fully-qualified"}},
  {U'🍯', { "honey pot","fully-qualified"}},
  {U'🥽', { "goggles","fully-qualified"}},
  {U'🏜', { "desert","unqualified"}},
  {U'🐅', { "tiger","fully-qualified"}},
  {U'♓', { "Pisces","fully-qualified"}},
  {U'🍚', { "cooked rice","fully-qualified"}},
  {U'🎡', { "ferris wheel","fully-qualified"}},
  {U'🐰', { "rabbit face","fully-qualified"}},
  {U'⛽', { "fuel pump","fully-qualified"}},
  {U'🏆', { "trophy","fully-qualified"}},
  {U'😉', { "winking face","fully-qualified"}},
  {U'🏽', { "medium skin tone","component"}},
  {U'🔀', { "shuffle tracks button","fully-qualified"}},
  {U'📍', { "round pushpin","fully-qualified"}},
  {U'🙈', { "see-no-evil monkey","fully-qualified"}},
  {U'👷', { "construction worker","fully-qualified"}},
  {U'🏣', { "Japanese post office","fully-qualified"}},
  {U'👀', { "eyes","fully-qualified"}},
  {U'🦊', { "fox","fully-qualified"}},
  {U'🤸', { "person cartwheeling","fully-qualified"}},
  {U'🎁', { "wrapped gift","fully-qualified"}},
  {U'🚦', { "vertical traffic light","fully-qualified"}},
  {U'💞', { "revolving hearts","fully-qualified"}},
  {U'🙍', { "person frowning","fully-qualified"}},
  {U'🔣', { "input symbols","fully-qualified"}},
  {U'👣', { "footprints","fully-qualified"}},
  {U'🍾', { "bottle with popping cork","fully-qualified"}},
  {U'🍙', { "rice ball","fully-qualified"}},
  {U'🚓', { "police car","fully-qualified"}},
  {U'🤱', { "breast-feeding","fully-qualified"}},
  {U'🌫', { "fog","unqualified"}},
  {U'😵', { "face with crossed-out eyes","fully-qualified"}},
  {U'🌿', { "herb","fully-qualified"}},
  {U'🐫', { "two-hump camel","fully-qualified"}},
  {U'🪩', { "mirror ball","fully-qualified"}},
  {U'🧔', { "person: beard","fully-qualified"}},
  {U'🚤', { "speedboat","fully-qualified"}},
  {U'🧨', { "firecracker","fully-qualified"}},
  {U'🐗', { "boar","fully-qualified"}},
  {U'🐠', { "tropical fish","fully-qualified"}},
  {U'🚾', { "water closet","fully-qualified"}},
  {U'📻', { "radio","fully-qualified"}},
  {U'🙅', { "person gesturing NO","fully-qualified"}},
  {U'🚹', { "men’s room","fully-qualified"}},
  {U'🍝', { "spaghetti","fully-qualified"}},
  {U'🖱', { "computer mouse","unqualified"}},
  {U'💵', { "dollar banknote","fully-qualified"}},
  {U'🚎', { "trolleybus","fully-qualified"}},
  {U'🈚', { "Japanese “free of charge” button","fully-qualified"}},
  {U'⭕', { "hollow red circle","fully-qualified"}},
  {U'💏', { "kiss","fully-qualified"}},
  {U'🍃', { "leaf fluttering in wind","fully-qualified"}},
  {U'🪝', { "hook","fully-qualified"}},
  {U'🦳', { "white hair","component"}},
  {U'◽', { "white medium-small square","fully-qualified"}},
  {U'🅿', { "P button","unqualified"}},
  {U'💜', { "purple heart","fully-qualified"}},
  {U'📎', { "paperclip","fully-qualified"}},
  {U'™', { "trade mark","unqualified"}},
  {U'⏫', { "fast up button","fully-qualified"}},
  {U'🌜', { "last quarter moon face","fully-qualified"}},
  {U'🦲', { "bald","component"}},
  {U'🥧', { "pie","fully-qualified"}},
  {U'🦹', { "supervillain","fully-qualified"}},
  {U'😩', { "weary face","fully-qualified"}},
  {U'🈳', { "Japanese “vacancy” button","fully-qualified"}},
  {U'🤒', { "face with thermometer","fully-qualified"}},
  {U'🫔', { "tamale","fully-qualified"}},
  {U'☹', { "frowning face","unqualified"}},
  {U'🏾', { "medium-dark skin tone","component"}},
  {U'🐦', { "bird","fully-qualified"}},
  {U'🩳', { "shorts","fully-qualified"}},
  {U'🚲', { "bicycle","fully-qualified"}},
  {U'🌉', { "bridge at night","fully-qualified"}},
  {U'🐍', { "snake","fully-qualified"}},
  {U'🪗', { "accordion","fully-qualified"}},
  {U'🏧', { "ATM sign","fully-qualified"}},
  {U'💄', { "lipstick","fully-qualified"}},
  {U'🫏', { "donkey","fully-qualified"}},
  {U'🏙', { "cityscape","unqualified"}},
  {U'®', { "registered","unqualified"}},
  {U'🎃', { "jack-o-lantern","fully-qualified"}},
  {U'🕓', { "four o’clock","fully-qualified"}},
  {U'🍁', { "maple leaf","fully-qualified"}},
  {U'🏁', { "chequered flag","fully-qualified"}},
  {U'➡', { "right arrow","unqualified"}},
  {U'👭', { "women holding hands","fully-qualified"}},
  {U'🌼', { "blossom","fully-qualified"}},
  {U'🪄', { "magic wand","fully-qualified"}},
  {U'🥲', { "smiling face with tear","fully-qualified"}},
  {U'🚛', { "articulated lorry","fully-qualified"}},
  {U'📥', { "inbox tray","fully-qualified"}},
  {U'😢', { "crying face","fully-qualified"}},
  {U'🌊', { "water wave","fully-qualified"}},
  {U'🔛', { "ON! arrow","fully-qualified"}},
  {U'⚕', { "medical symbol","unqualified"}},
  {U'👮', { "police officer","fully-qualified"}},
  {U'🪔', { "diya lamp","fully-qualified"}},
  {U'😧', { "anguished face","fully-qualified"}},
  {U'🏨', { "hotel","fully-qualified"}},
  {U'🍱', { "bento box","fully-qualified"}},
  {U'💯', { "hundred points","fully-qualified"}},
  {U'🦻', { "ear with hearing aid","fully-qualified"}},
  {U'🙆', { "person gesturing OK","fully-qualified"}},
  {U'🧜', { "merperson","fully-qualified"}},
  {U'♂', { "male sign","unqualified"}},
  {U'🦆', { "duck","fully-qualified"}},
  {U'🍌', { "banana","fully-qualified"}},
  {U'📝', { "memo","fully-qualified"}},
  {U'😯', { "hushed face","fully-qualified"}},
  {U'🌂', { "closed umbrella","fully-qualified"}},
  {U'🗃', { "card file box","unqualified"}},
  {U'㊙', { "Japanese “secret” button","unqualified"}},
  {U'🧬', { "dna","fully-qualified"}},
  {U'🌁', { "foggy","fully-qualified"}},
  {U'🐩', { "poodle","fully-qualified"}},
  {U'🐭', { "mouse face","fully-qualified"}},
  {U'🥒', { "cucumber","fully-qualified"}},
  {U'⌚', { "watch","fully-qualified"}},
  {U'🗂', { "card index dividers","unqualified"}},
  {U'😞', { "disappointed face","fully-qualified"}},
  {U'😋', { "face savoring food","fully-qualified"}},
  {U'🍉', { "watermelon","fully-qualified"}},
  {U'👢', { "woman’s boot","fully-qualified"}},
  {U'📷', { "camera","fully-qualified"}},
  {U'🔭', { "telescope","fully-qualified"}},
  {U'👓', { "glasses","fully-qualified"}},
  {U'🥐', { "croissant","fully-qualified"}},
  {U'🥺', { "pleading face","fully-qualified"}},
  {U'🤣', { "rolling on the floor laughing","fully-qualified"}},
  {U'👱', { "person: blond hair","fully-qualified"}},
  {U'🛖', { "hut","fully-qualified"}},
  {U'🏮', { "red paper lantern","fully-qualified"}},
  {U'🏒', { "ice hockey","fully-qualified"}},
  {U'🎱', { "pool 8 ball","fully-qualified"}},
  {U'⛄', { "snowman without snow","fully-qualified"}},
  {U'🐜', { "ant","fully-qualified"}},
  {U'📇', { "card index","fully-qualified"}},
//  {U'#⃣', { "keycap: #","unqualified"}},
  {U'🪆', { "nesting dolls","fully-qualified"}},
  {U'💡', { "light bulb","fully-qualified"}},
  {U'👧', { "girl","fully-qualified"}},
  {U'🏡', { "house with garden","fully-qualified"}},
  {U'👞', { "man’s shoe","fully-qualified"}},
  {U'⏪', { "fast reverse button","fully-qualified"}},
  {U'🟫', { "brown square","fully-qualified"}},
  {U'🌴', { "palm tree","fully-qualified"}},
  {U'🕕', { "six o’clock","fully-qualified"}},
  {U'🖌', { "paintbrush","unqualified"}},
  {U'🗳', { "ballot box with ballot","unqualified"}},
  {U'🥏', { "flying disc","fully-qualified"}},
  {U'🚼', { "baby symbol","fully-qualified"}},
  {U'💫', { "dizzy","fully-qualified"}},
  {U'🐱', { "cat face","fully-qualified"}},
  {U'🧤', { "gloves","fully-qualified"}},
  {U'😎', { "smiling face with sunglasses","fully-qualified"}},
  {U'🎟', { "admission tickets","unqualified"}},
  {U'🔯', { "dotted six-pointed star","fully-qualified"}},
  {U'⚱', { "funeral urn","unqualified"}},
  {U'✊', { "raised fist","fully-qualified"}},
  {U'🍄', { "mushroom","fully-qualified"}},
  {U'💿', { "optical disk","fully-qualified"}},
  {U'⚓', { "anchor","fully-qualified"}},
  {U'👕', { "t-shirt","fully-qualified"}},
  {U'▫', { "white small square","unqualified"}},
  {U'🌀', { "cyclone","fully-qualified"}},
  {U'🚜', { "tractor","fully-qualified"}},
  {U'📠', { "fax machine","fully-qualified"}},
  {U'🪹', { "empty nest","fully-qualified"}},
  {U'🎋', { "tanabata tree","fully-qualified"}},
  {U'🚟', { "suspension railway","fully-qualified"}},
  {U'🚊', { "tram","fully-qualified"}},
  {U'🏉', { "rugby football","fully-qualified"}},
  {U'📙', { "orange book","fully-qualified"}},
  {U'🐴', { "horse face","fully-qualified"}},
  {U'🚌', { "bus","fully-qualified"}},
  {U'♥', { "heart suit","unqualified"}},
  {U'😠', { "angry face","fully-qualified"}},
  {U'🍖', { "meat on bone","fully-qualified"}},
  {U'👘', { "kimono","fully-qualified"}},
  {U'🚕', { "taxi","fully-qualified"}},
  {U'🏥', { "hospital","fully-qualified"}},
  {U'🔝', { "TOP arrow","fully-qualified"}},
  {U'🦑', { "squid","fully-qualified"}},
  {U'🌱', { "seedling","fully-qualified"}},
  {U'🗑', { "wastebasket","unqualified"}},
  {U'🚗', { "automobile","fully-qualified"}},
  {U'🥚', { "egg","fully-qualified"}},
  {U'📆', { "tear-off calendar","fully-qualified"}},
  {U'🔳', { "white square button","fully-qualified"}},
  {U'🫱', { "rightwards hand","fully-qualified"}},
  {U'📳', { "vibration mode","fully-qualified"}},
  {U'🐙', { "octopus","fully-qualified"}},
  {U'🦢', { "swan","fully-qualified"}},
  {U'🪢', { "knot","fully-qualified"}},
  {U'👶', { "baby","fully-qualified"}},
  {U'🧮', { "abacus","fully-qualified"}},
  {U'🐀', { "rat","fully-qualified"}},
  {U'🍫', { "chocolate bar","fully-qualified"}},
  {U'🔂', { "repeat single button","fully-qualified"}},
  {U'⏭', { "next track button","unqualified"}},
  {U'🥵', { "hot face","fully-qualified"}},
  {U'🧦', { "socks","fully-qualified"}},
  {U'🔻', { "red triangle pointed down","fully-qualified"}},
  {U'🥯', { "bagel","fully-qualified"}},
  {U'⏳', { "hourglass not done","fully-qualified"}},
  {U'👇', { "backhand index pointing down","fully-qualified"}},
  {U'🐻', { "bear","fully-qualified"}},
  {U'🛬', { "airplane arrival","fully-qualified"}},
  {U'🤘', { "sign of the horns","fully-qualified"}},
  {U'🐢', { "turtle","fully-qualified"}},
  {U'😑', { "expressionless face","fully-qualified"}},
  {U'👗', { "dress","fully-qualified"}},
  {U'🚈', { "light rail","fully-qualified"}},
  {U'🏏', { "cricket game","fully-qualified"}},
  {U'👈', { "backhand index pointing left","fully-qualified"}},
  {U'🫧', { "bubbles","fully-qualified"}},
  {U'🎨', { "artist palette","fully-qualified"}},
  {U'🍰', { "shortcake","fully-qualified"}},
  {U'📯', { "postal horn","fully-qualified"}},
  {U'🎼', { "musical score","fully-qualified"}},
  {U'🦵', { "leg","fully-qualified"}},
  {U'🎣', { "fishing pole","fully-qualified"}},
  {U'💳', { "credit card","fully-qualified"}},
  {U'🟦', { "blue square","fully-qualified"}},
  {U'㊗', { "Japanese “congratulations” button","unqualified"}},
  {U'🅾', { "O button (blood type)","unqualified"}},
  {U'〽', { "part alternation mark","unqualified"}},
  {U'📮', { "postbox","fully-qualified"}},
  {U'🍗', { "poultry leg","fully-qualified"}},
  {U'📌', { "pushpin","fully-qualified"}},
  {U'🧐', { "face with monocle","fully-qualified"}},
  {U'📨', { "incoming envelope","fully-qualified"}},
  {U'💘', { "heart with arrow","fully-qualified"}},
  {U'🕟', { "four-thirty","fully-qualified"}},
  {U'🛋', { "couch and lamp","unqualified"}},
  {U'🧾', { "receipt","fully-qualified"}},
  {U'⚪', { "white circle","fully-qualified"}},
  {U'🎖', { "military medal","unqualified"}},
  {U'🔎', { "magnifying glass tilted right","fully-qualified"}},
  {U'🚮', { "litter in bin sign","fully-qualified"}},
  {U'🏬', { "department store","fully-qualified"}},
  {U'💭', { "thought balloon","fully-qualified"}},
  {U'🧇', { "waffle","fully-qualified"}},
  {U'🤥', { "lying face","fully-qualified"}},
  {U'🆔', { "ID button","fully-qualified"}},
  {U'😍', { "smiling face with heart-eyes","fully-qualified"}},
  {U'🆎', { "AB button (blood type)","fully-qualified"}},
  {U'👹', { "ogre","fully-qualified"}},
  {U'🤨', { "face with raised eyebrow","fully-qualified"}},
  {U'🥖', { "baguette bread","fully-qualified"}},
  {U'🦶', { "foot","fully-qualified"}},
  {U'🧸', { "teddy bear","fully-qualified"}},
  {U'⏲', { "timer clock","unqualified"}},
  {U'🏼', { "medium-light skin tone","component"}},
  {U'🫅', { "person with crown","fully-qualified"}},
  {U'🏕', { "camping","unqualified"}},
  {U'🫦', { "biting lip","fully-qualified"}},
  {U'🐋', { "whale","fully-qualified"}},
  {U'🕑', { "two o’clock","fully-qualified"}},
  {U'🎩', { "top hat","fully-qualified"}},
  {U'✌', { "victory hand","unqualified"}},
  {U'🔏', { "locked with pen","fully-qualified"}},
  {U'😃', { "grinning face with big eyes","fully-qualified"}},
  {U'🧕', { "woman with headscarf","fully-qualified"}},
  {U'🏊', { "person swimming","fully-qualified"}},
  {U'💝', { "heart with ribbon","fully-qualified"}},
  {U'♠', { "spade suit","unqualified"}},
  {U'🏦', { "bank","fully-qualified"}},
  {U'🤑', { "money-mouth face","fully-qualified"}},
  {U'👆', { "backhand index pointing up","fully-qualified"}},
  {U'🍹', { "tropical drink","fully-qualified"}},
  {U'👜', { "handbag","fully-qualified"}},
  {U'💔', { "broken heart","fully-qualified"}},
  {U'😅', { "grinning face with sweat","fully-qualified"}},
  {U'🔓', { "unlocked","fully-qualified"}},
  {U'🍭', { "lollipop","fully-qualified"}},
  {U'🚷', { "no pedestrians","fully-qualified"}},
  {U'🥤', { "cup with straw","fully-qualified"}},
  {U'🫥', { "dotted line face","fully-qualified"}},
  {U'◼', { "black medium square","unqualified"}},
  {U'🚡', { "aerial tramway","fully-qualified"}},
  {U'🔥', { "fire","fully-qualified"}},
  {U'🎓', { "graduation cap","fully-qualified"}},
  {U'🙇', { "person bowing","fully-qualified"}},
  {U'🎉', { "party popper","fully-qualified"}},
  {U'🥙', { "stuffed flatbread","fully-qualified"}},
  {U'🧗', { "person climbing","fully-qualified"}},
  {U'😗', { "kissing face","fully-qualified"}},
  {U'🟨', { "yellow square","fully-qualified"}},
  {U'😲', { "astonished face","fully-qualified"}},
  {U'🔫', { "water pistol","fully-qualified"}},
  {U'👝', { "clutch bag","fully-qualified"}},
  {U'🧖', { "person in steamy room","fully-qualified"}},
  {U'🏰', { "castle","fully-qualified"}},
  {U'🟠', { "orange circle","fully-qualified"}},
  {U'🧚', { "fairy","fully-qualified"}},
  {U'🫠', { "melting face","fully-qualified"}},
  {U'🦪', { "oyster","fully-qualified"}},
  {U'😣', { "persevering face","fully-qualified"}},
  {U'🛥', { "motor boat","unqualified"}},
  {U'👠', { "high-heeled shoe","fully-qualified"}},
  {U'💂', { "guard","fully-qualified"}},
  {U'🛏', { "bed","unqualified"}},
  {U'🍍', { "pineapple","fully-qualified"}},
  {U'🎌', { "crossed flags","fully-qualified"}},
  {U'🦩', { "flamingo","fully-qualified"}},
  {U'🛤', { "railway track","unqualified"}},
  {U'✂', { "scissors","unqualified"}},
  {U'➗', { "divide","fully-qualified"}},
  {U'🎙', { "studio microphone","unqualified"}},
  {U'🩲', { "briefs","fully-qualified"}},
  {U'🤰', { "pregnant woman","fully-qualified"}},
  {U'🍘', { "rice cracker","fully-qualified"}},
  {U'🐸', { "frog","fully-qualified"}},
  {U'😽', { "kissing cat","fully-qualified"}},
  {U'🏗', { "building construction","unqualified"}},
  {U'🗺', { "world map","unqualified"}},
  {U'♌', { "Leo","fully-qualified"}},
  {U'🕠', { "five-thirty","fully-qualified"}},
  {U'🚥', { "horizontal traffic light","fully-qualified"}},
  {U'🧛', { "vampire","fully-qualified"}},
  {U'🚄', { "high-speed train","fully-qualified"}},
  {U'🥹', { "face holding back tears","fully-qualified"}},
  {U'⛔', { "no entry","fully-qualified"}},
  {U'🚑', { "ambulance","fully-qualified"}},
  {U'♻', { "recycling symbol","unqualified"}},
  {U'🍐', { "pear","fully-qualified"}},
  {U'🦿', { "mechanical leg","fully-qualified"}},
  {U'🦉', { "owl","fully-qualified"}},
  {U'🧢', { "billed cap","fully-qualified"}},
  {U'🩹', { "adhesive bandage","fully-qualified"}},
  {U'⛑', { "rescue worker’s helmet","unqualified"}},
  {U'🐿', { "chipmunk","unqualified"}},
  {U'🕎', { "menorah","fully-qualified"}},
  {U'🚧', { "construction","fully-qualified"}},
  {U'🗄', { "file cabinet","unqualified"}},
  {U'🟧', { "orange square","fully-qualified"}},
  {U'🪷', { "lotus","fully-qualified"}},
  {U'🐹', { "hamster","fully-qualified"}},
  {U'💹', { "chart increasing with yen","fully-qualified"}},
  {U'♣', { "club suit","unqualified"}},
  {U'🖲', { "trackball","unqualified"}},
  {U'🦧', { "orangutan","fully-qualified"}},
  {U'👥', { "busts in silhouette","fully-qualified"}},
  {U'🤟', { "love-you gesture","fully-qualified"}},
  {U'🎇', { "sparkler","fully-qualified"}},
  {U'🔸', { "small orange diamond","fully-qualified"}},
  {U'⏯', { "play or pause button","unqualified"}},
  {U'🤯', { "exploding head","fully-qualified"}},
  {U'🥊', { "boxing glove","fully-qualified"}},
  {U'🪲', { "beetle","fully-qualified"}},
  {U'🦰', { "red hair","component"}},
  {U'🧽', { "sponge","fully-qualified"}},
  {U'👾', { "alien monster","fully-qualified"}},
  {U'⚒', { "hammer and pick","unqualified"}},
  {U'🛕', { "hindu temple","fully-qualified"}},
  {U'🏢', { "office building","fully-qualified"}},
  {U'↖', { "up-left arrow","unqualified"}},
  {U'🍈', { "melon","fully-qualified"}},
//  {U'5⃣', { "keycap: 5","unqualified"}},
  {U'🏍', { "motorcycle","unqualified"}},
  {U'⏹', { "stop button","unqualified"}},
  {U'✔', { "check mark","unqualified"}},
  {U'⬜', { "white large square","fully-qualified"}},
  {U'🌯', { "burrito","fully-qualified"}},
  {U'🚳', { "no bicycles","fully-qualified"}},
  {U'🕹', { "joystick","unqualified"}},
  {U'🛡', { "shield","unqualified"}},
  {U'🦬', { "bison","fully-qualified"}},
  {U'🪰', { "fly","fully-qualified"}},
  {U'🙃', { "upside-down face","fully-qualified"}},
  {U'🪒', { "razor","fully-qualified"}},
  {U'⛎', { "Ophiuchus","fully-qualified"}},
  {U'🚵', { "person mountain biking","fully-qualified"}},
  {U'👛', { "purse","fully-qualified"}},
  {U'🔧', { "wrench","fully-qualified"}},
  {U'🥑', { "avocado","fully-qualified"}},
  {U'📔', { "notebook with decorative cover","fully-qualified"}},
  {U'🤓', { "nerd face","fully-qualified"}},
  {U'🏝', { "desert island","unqualified"}},
  {U'🧺', { "basket","fully-qualified"}},
  {U'🔘', { "radio button","fully-qualified"}},
  {U'📦', { "package","fully-qualified"}},
  {U'☯', { "yin yang","unqualified"}},
  {U'🐼', { "panda","fully-qualified"}},
  {U'⌨', { "keyboard","unqualified"}},
  {U'🏚', { "derelict house","unqualified"}},
  {U'💶', { "euro banknote","fully-qualified"}},
  {U'🉐', { "Japanese “bargain” button","fully-qualified"}},
  {U'😮', { "face with open mouth","fully-qualified"}},
  {U'☘', { "shamrock","unqualified"}},
  {U'🥗', { "green salad","fully-qualified"}},
  {U'➿', { "double curly loop","fully-qualified"}},
  {U'💣', { "bomb","fully-qualified"}},
  {U'🪯', { "khanda","fully-qualified"}},
  {U'🚐', { "minibus","fully-qualified"}},
  {U'🦥', { "sloth","fully-qualified"}},
  {U'🈵', { "Japanese “no vacancy” button","fully-qualified"}},
  {U'🫢', { "face with open eyes and hand over mouth","fully-qualified"}},
  {U'🍎', { "red apple","fully-qualified"}},
  {U'🎫', { "ticket","fully-qualified"}},
  {U'🍟', { "french fries","fully-qualified"}},
  {U'✳', { "eight-spoked asterisk","unqualified"}},
  {U'🐽', { "pig nose","fully-qualified"}},
  {U'👰', { "person with veil","fully-qualified"}},
  {U'🧆', { "falafel","fully-qualified"}},
  {U'⚜', { "fleur-de-lis","unqualified"}},
  {U'🩷', { "pink heart","fully-qualified"}},
  {U'◾', { "black medium-small square","fully-qualified"}},
  {U'🛝', { "playground slide","fully-qualified"}},
  {U'🥎', { "softball","fully-qualified"}},
  {U'➰', { "curly loop","fully-qualified"}},
  {U'💕', { "two hearts","fully-qualified"}},
  {U'💻', { "laptop","fully-qualified"}},
  {U'🕍', { "synagogue","fully-qualified"}},
  {U'🪓', { "axe","fully-qualified"}},
  {U'🐓', { "rooster","fully-qualified"}},
  {U'📢', { "loudspeaker","fully-qualified"}},
  {U'🛑', { "stop sign","fully-qualified"}},
  {U'🍩', { "doughnut","fully-qualified"}},
  {U'🐆', { "leopard","fully-qualified"}},
  {U'⚫', { "black circle","fully-qualified"}},
  {U'🚙', { "sport utility vehicle","fully-qualified"}},
  {U'🫘', { "beans","fully-qualified"}},
  {U'⬇', { "down arrow","unqualified"}},
  {U'📅', { "calendar","fully-qualified"}},
  {U'😐', { "neutral face","fully-qualified"}},
  {U'🖋', { "fountain pen","unqualified"}},
  {U'🤹', { "person juggling","fully-qualified"}},
  {U'🚿', { "shower","fully-qualified"}},
  {U'🤮', { "face vomiting","fully-qualified"}},
  {U'🗓', { "spiral calendar","unqualified"}},
  {U'😦', { "frowning face with open mouth","fully-qualified"}},
  {U'🛢', { "oil drum","unqualified"}},
  {U'🐞', { "lady beetle","fully-qualified"}},
  {U'🥷', { "ninja","fully-qualified"}},
  {U'🫓', { "flatbread","fully-qualified"}},
  {U'🌬', { "wind face","unqualified"}},
  {U'🕞', { "three-thirty","fully-qualified"}},
  {U'🫣', { "face with peeking eye","fully-qualified"}},
  {U'🥭', { "mango","fully-qualified"}},
  {U'🧫', { "petri dish","fully-qualified"}},
  {U'🍻', { "clinking beer mugs","fully-qualified"}},
  {U'🎚', { "level slider","unqualified"}},
  {U'🧷', { "safety pin","fully-qualified"}},
  {U'🩰', { "ballet shoes","fully-qualified"}},
  {U'💋', { "kiss mark","fully-qualified"}},
  {U'🔞', { "no one under eighteen","fully-qualified"}},
  {U'⛈', { "cloud with lightning and rain","unqualified"}},
  {U'🫃', { "pregnant man","fully-qualified"}},
  {U'🧙', { "mage","fully-qualified"}},
  {U'🛷', { "sled","fully-qualified"}},
  {U'🤐', { "zipper-mouth face","fully-qualified"}},
  {U'⏺', { "record button","unqualified"}},
  {U'⛹', { "person bouncing ball","unqualified"}},
  {U'🉑', { "Japanese “acceptable” button","fully-qualified"}},
  {U'🗜', { "clamp","unqualified"}},
  {U'🐂', { "ox","fully-qualified"}},
  {U'↗', { "up-right arrow","unqualified"}},
  {U'🩱', { "one-piece swimsuit","fully-qualified"}},
  {U'💾', { "floppy disk","fully-qualified"}},
  {U'🈺', { "Japanese “open for business” button","fully-qualified"}},
  {U'🍕', { "pizza","fully-qualified"}},
  {U'📺', { "television","fully-qualified"}},
  {U'🤜', { "right-facing fist","fully-qualified"}},
  {U'🛣', { "motorway","unqualified"}},
  {U'👼', { "baby angel","fully-qualified"}},
  {U'💷', { "pound banknote","fully-qualified"}},
  {U'✏', { "pencil","unqualified"}},
  {U'🌐', { "globe with meridians","fully-qualified"}},
  {U'💬', { "speech balloon","fully-qualified"}},
  {U'🧣', { "scarf","fully-qualified"}},
  {U'🦎', { "lizard","fully-qualified"}},
  {U'🪽', { "wing","fully-qualified"}},
  {U'💇', { "person getting haircut","fully-qualified"}},
  {U'🚭', { "no smoking","fully-qualified"}},
  {U'😙', { "kissing face with smiling eyes","fully-qualified"}},
  {U'📰', { "newspaper","fully-qualified"}},
  {U'🤽', { "person playing water polo","fully-qualified"}},
  {U'🌟', { "glowing star","fully-qualified"}},
  {U'🐤', { "baby chick","fully-qualified"}},
  {U'🐲', { "dragon face","fully-qualified"}},
  {U'📜', { "scroll","fully-qualified"}},
  {U'🌒', { "waxing crescent moon","fully-qualified"}},
  {U'🧯', { "fire extinguisher","fully-qualified"}},
  {U'📟', { "pager","fully-qualified"}},
  {U'🧃', { "beverage box","fully-qualified"}},
  {U'🪃', { "boomerang","fully-qualified"}},
  {U'🈯', { "Japanese “reserved” button","fully-qualified"}},
  {U'🕙', { "ten o’clock","fully-qualified"}},
  {U'🐊', { "crocodile","fully-qualified"}},
  {U'📋', { "clipboard","fully-qualified"}},
  {U'🦓', { "zebra","fully-qualified"}},
  {U'💨', { "dashing away","fully-qualified"}},
  {U'😟', { "worried face","fully-qualified"}},
  {U'🤦', { "person facepalming","fully-qualified"}},
  {U'🥩', { "cut of meat","fully-qualified"}},
  {U'🆘', { "SOS button","fully-qualified"}},
  {U'⛪', { "church","fully-qualified"}},
  {U'🏔', { "snow-capped mountain","unqualified"}},
  {U'🕋', { "kaaba","fully-qualified"}},
  {U'🤪', { "zany face","fully-qualified"}},
  {U'😛', { "face with tongue","fully-qualified"}},
  {U'🍠', { "roasted sweet potato","fully-qualified"}},
  {U'🍸', { "cocktail glass","fully-qualified"}},
  {U'🐧', { "penguin","fully-qualified"}},
  {U'🔈', { "speaker low volume","fully-qualified"}},
  {U'🐟', { "fish","fully-qualified"}},
  {U'👂', { "ear","fully-qualified"}},
  {U'🗣', { "speaking head","unqualified"}},
  {U'🛂', { "passport control","fully-qualified"}},
  {U'🪭', { "folding hand fan","fully-qualified"}},
  {U'🐳', { "spouting whale","fully-qualified"}},
  {U'💲', { "heavy dollar sign","fully-qualified"}},
  {U'😌', { "relieved face","fully-qualified"}},
  {U'❤', { "red heart","unqualified"}},
  {U'💛', { "yellow heart","fully-qualified"}},
  {U'🎤', { "microphone","fully-qualified"}},
  {U'📩', { "envelope with arrow","fully-qualified"}},
  {U'🙊', { "speak-no-evil monkey","fully-qualified"}},
  {U'🤬', { "face with symbols on mouth","fully-qualified"}},
  {U'🦄', { "unicorn","fully-qualified"}},
  {U'🔖', { "bookmark","fully-qualified"}},
  {U'🥌', { "curling stone","fully-qualified"}},
  {U'📭', { "open mailbox with lowered flag","fully-qualified"}},
  {U'❌', { "cross mark","fully-qualified"}},
  {U'🎺', { "trumpet","fully-qualified"}},
  {U'🔌', { "electric plug","fully-qualified"}},
  {U'💉', { "syringe","fully-qualified"}},
  {U'📄', { "page facing up","fully-qualified"}},
  {U'🚋', { "tram car","fully-qualified"}},
  {U'🌑', { "new moon","fully-qualified"}},
  {U'🦖', { "T-Rex","fully-qualified"}},
  {U'⛵', { "sailboat","fully-qualified"}},
  {U'🙉', { "hear-no-evil monkey","fully-qualified"}},
  {U'🔇', { "muted speaker","fully-qualified"}},
  {U'🛸', { "flying saucer","fully-qualified"}},
  {U'🎠', { "carousel horse","fully-qualified"}},
//  {U'3⃣', { "keycap: 3","unqualified"}},
  {U'❕', { "white exclamation mark","fully-qualified"}},
  {U'💤', { "ZZZ","fully-qualified"}},
  {U'😥', { "sad but relieved face","fully-qualified"}},
  {U'🗾', { "map of Japan","fully-qualified"}},
  {U'🐣', { "hatching chick","fully-qualified"}},
  {U'🫳', { "palm down hand","fully-qualified"}},
  {U'🏄', { "person surfing","fully-qualified"}},
  {U'👬', { "men holding hands","fully-qualified"}},
  {U'😁', { "beaming face with smiling eyes","fully-qualified"}},
//  {U'*⃣', { "keycap: *","unqualified"}},
  {U'♍', { "Virgo","fully-qualified"}},
  {U'🚯', { "no littering","fully-qualified"}},
  {U'👩', { "woman","fully-qualified"}},
  {U'🏅', { "sports medal","fully-qualified"}},
  {U'🪙', { "coin","fully-qualified"}},
  {U'🚇', { "metro","fully-qualified"}},
  {U'👉', { "backhand index pointing right","fully-qualified"}},
  {U'📽', { "film projector","unqualified"}},
  {U'🙄', { "face with rolling eyes","fully-qualified"}},
  {U'🐮', { "cow face","fully-qualified"}},
  {U'🦸', { "superhero","fully-qualified"}},
  {U'🌅', { "sunrise","fully-qualified"}},
  {U'📫', { "closed mailbox with raised flag","fully-qualified"}},
  {U'📐', { "triangular ruler","fully-qualified"}},
  {U'🪇', { "maracas","fully-qualified"}},
  {U'🫰', { "hand with index finger and thumb crossed","fully-qualified"}},
  {U'🧒', { "child","fully-qualified"}},
  {U'👐', { "open hands","fully-qualified"}},
  {U'🖼', { "framed picture","unqualified"}},
  {U'🫒', { "olive","fully-qualified"}},
  {U'🧀', { "cheese wedge","fully-qualified"}},
  {U'🪱', { "worm","fully-qualified"}},
  {U'🤴', { "prince","fully-qualified"}},
  {U'🏠', { "house","fully-qualified"}},
  {U'😺', { "grinning cat","fully-qualified"}},
  {U'🛟', { "ring buoy","fully-qualified"}},
  {U'☸', { "wheel of dharma","unqualified"}},
  {U'⛓', { "chains","unqualified"}},
  {U'🤶', { "Mrs. Claus","fully-qualified"}},
  {U'🦯', { "white cane","fully-qualified"}},
  {U'🪤', { "mouse trap","fully-qualified"}},
  {U'🔋', { "battery","fully-qualified"}},
  {U'🔲', { "black square button","fully-qualified"}},
  {U'😼', { "cat with wry smile","fully-qualified"}},
  {U'♟', { "chess pawn","unqualified"}},
  {U'🍽', { "fork and knife with plate","unqualified"}},
  {U'🐬', { "dolphin","fully-qualified"}},
  {U'🛠', { "hammer and wrench","unqualified"}},
  {U'📱', { "mobile phone","fully-qualified"}},
  {U'🛗', { "elevator","fully-qualified"}},
  {U'🕯', { "candle","unqualified"}},
  {U'🦔', { "hedgehog","fully-qualified"}},
  {U'📊', { "bar chart","fully-qualified"}},
  {U'🔪', { "kitchen knife","fully-qualified"}},
  {U'😔', { "pensive face","fully-qualified"}},
  {U'💦', { "sweat droplets","fully-qualified"}},
  {U'🕰', { "mantelpiece clock","unqualified"}},
  {U'☔', { "umbrella with rain drops","fully-qualified"}},
  {U'♋', { "Cancer","fully-qualified"}},
  {U'⚰', { "coffin","unqualified"}},
  {U'🪬', { "hamsa","fully-qualified"}},
  {U'🚢', { "ship","fully-qualified"}},
  {U'🏘', { "houses","unqualified"}},
  {U'©', { "copyright","unqualified"}},
  {U'😤', { "face with steam from nose","fully-qualified"}},
  {U'👲', { "person with skullcap","fully-qualified"}},
  {U'♦', { "diamond suit","unqualified"}},
  {U'🔟', { "keycap: 10","fully-qualified"}},
  {U'🕌', { "mosque","fully-qualified"}},
  {U'🙁', { "slightly frowning face","fully-qualified"}},
  {U'🛳', { "passenger ship","unqualified"}},
  {U'🆗', { "OK button","fully-qualified"}},
  {U'🍬', { "candy","fully-qualified"}},
  {U'🛄', { "baggage claim","fully-qualified"}},
  {U'🛐', { "place of worship","fully-qualified"}},
  {U'🍢', { "oden","fully-qualified"}},
  {U'🎀', { "ribbon","fully-qualified"}},
  {U'😆', { "grinning squinting face","fully-qualified"}},
  {U'🙎', { "person pouting","fully-qualified"}},
  {U'👡', { "woman’s sandal","fully-qualified"}},
  {U'🧉', { "mate","fully-qualified"}},
  {U'🌦', { "sun behind rain cloud","unqualified"}},
  {U'👫', { "woman and man holding hands","fully-qualified"}},
  {U'🚘', { "oncoming automobile","fully-qualified"}},
  {U'🟣', { "purple circle","fully-qualified"}},
  {U'🦞', { "lobster","fully-qualified"}},
  {U'🧍', { "person standing","fully-qualified"}},
  {U'🔉', { "speaker medium volume","fully-qualified"}},
  {U'🍵', { "teacup without handle","fully-qualified"}},
  {U'🏀', { "basketball","fully-qualified"}},
  {U'🚃', { "railway car","fully-qualified"}},
  {U'🍊', { "tangerine","fully-qualified"}},
  {U'🍨', { "ice cream","fully-qualified"}},
  {U'🎊', { "confetti ball","fully-qualified"}},
  {U'🪼', { "jellyfish","fully-qualified"}},
  {U'🎳', { "bowling","fully-qualified"}},
  {U'😈', { "smiling face with horns","fully-qualified"}},
  {U'📃', { "page with curl","fully-qualified"}},
  {U'🍔', { "hamburger","fully-qualified"}},
  {U'🦁', { "lion","fully-qualified"}},
  {U'🔔', { "bell","fully-qualified"}},
  {U'🕶', { "sunglasses","unqualified"}},
  {U'🎛', { "control knobs","unqualified"}},
  {U'🕡', { "six-thirty","fully-qualified"}},
  {U'🛀', { "person taking bath","fully-qualified"}},
  {U'🥿', { "flat shoe","fully-qualified"}},
  {U'❓', { "red question mark","fully-qualified"}},
  {U'🦛', { "hippopotamus","fully-qualified"}},
  {U'🔴', { "red circle","fully-qualified"}},
  {U'⛷', { "skier","unqualified"}},
  {U'🍛', { "curry rice","fully-qualified"}},
//  {U'7⃣', { "keycap: 7","unqualified"}},
  {U'😀', { "grinning face","fully-qualified"}},
  {U'☀', { "sun","unqualified"}},
  {U'☁', { "cloud","unqualified"}},
  {U'✡', { "star of David","unqualified"}},
  {U'🤎', { "brown heart","fully-qualified"}},
  {U'🎪', { "circus tent","fully-qualified"}},
  {U'🍡', { "dango","fully-qualified"}},
  {U'🎵', { "musical note","fully-qualified"}},
  {U'💆', { "person getting massage","fully-qualified"}},
  {U'👴', { "old man","fully-qualified"}},
  {U'🧁', { "cupcake","fully-qualified"}},
  {U'🍶', { "sake","fully-qualified"}},
  {U'🪴', { "potted plant","fully-qualified"}},
  {U'🪸', { "coral","fully-qualified"}},
  {U'👳', { "person wearing turban","fully-qualified"}},
  {U'📛', { "name badge","fully-qualified"}},
  {U'🥶', { "cold face","fully-qualified"}},
  {U'✨', { "sparkles","fully-qualified"}},
  {U'🌞', { "sun with face","fully-qualified"}},
  {U'🪫', { "low battery","fully-qualified"}},
  {U'🐶', { "dog face","fully-qualified"}},
  {U'🏖', { "beach with umbrella","unqualified"}},
  {U'💢', { "anger symbol","fully-qualified"}},
  {U'🦜', { "parrot","fully-qualified"}},
  {U'🐁', { "mouse","fully-qualified"}},
  {U'🔠', { "input latin uppercase","fully-qualified"}},
  {U'🐄', { "cow","fully-qualified"}},
  {U'🪦', { "headstone","fully-qualified"}},
  {U'🕴', { "person in suit levitating","unqualified"}},
  {U'🗼', { "Tokyo tower","fully-qualified"}},
  {U'🦠', { "microbe","fully-qualified"}},
  {U'📤', { "outbox tray","fully-qualified"}},
  {U'🃏', { "joker","fully-qualified"}},
  {U'😹', { "cat with tears of joy","fully-qualified"}},
  {U'✖', { "multiply","unqualified"}},
  {U'🌃', { "night with stars","fully-qualified"}},
  {U'😰', { "anxious face with sweat","fully-qualified"}},
  {U'📼', { "videocassette","fully-qualified"}},
  {U'🚻', { "restroom","fully-qualified"}},
  {U'🛜', { "wireless","fully-qualified"}},
  {U'🧋', { "bubble tea","fully-qualified"}},
  {U'🐯', { "tiger face","fully-qualified"}},
  {U'💪', { "flexed biceps","fully-qualified"}},
  {U'🪅', { "piñata","fully-qualified"}},
  {U'🤧', { "sneezing face","fully-qualified"}},
  {U'🥦', { "broccoli","fully-qualified"}},
  {U'🕳', { "hole","unqualified"}},
  {U'📒', { "ledger","fully-qualified"}},
  {U'🗝', { "old key","unqualified"}},
  {U'🪺', { "nest with eggs","fully-qualified"}},
  {U'💚', { "green heart","fully-qualified"}},
  {U'🥍', { "lacrosse","fully-qualified"}},
  {U'🗨', { "left speech bubble","unqualified"}},
  {U'🧪', { "test tube","fully-qualified"}},
  {U'♀', { "female sign","unqualified"}},
  {U'🍆', { "eggplant","fully-qualified"}},
  {U'💰', { "money bag","fully-qualified"}},
  {U'⤴', { "right arrow curving up","unqualified"}},
  {U'🧞', { "genie","fully-qualified"}},
  {U'🪘', { "long drum","fully-qualified"}},
  {U'‼', { "double exclamation mark","unqualified"}},
  {U'🖥', { "desktop computer","unqualified"}},
  {U'🖍', { "crayon","unqualified"}},
  {U'🆚', { "VS button","fully-qualified"}},
  {U'👏', { "clapping hands","fully-qualified"}},
  {U'🤫', { "shushing face","fully-qualified"}},
  {U'🦀', { "crab","fully-qualified"}},
  {U'🐎', { "horse","fully-qualified"}},
  {U'⚗', { "alembic","unqualified"}},
  {U'☝', { "index pointing up","unqualified"}},
  {U'🥻', { "sari","fully-qualified"}},
  {U'🫕', { "fondue","fully-qualified"}},
  {U'💓', { "beating heart","fully-qualified"}},
  {U'🧧', { "red envelope","fully-qualified"}},
  {U'🥬', { "leafy green","fully-qualified"}},
  {U'✒', { "black nib","unqualified"}},
  {U'🛅', { "left luggage","fully-qualified"}},
  {U'☄', { "comet","unqualified"}},
  {U'📹', { "video camera","fully-qualified"}},
  {U'🕉', { "om","unqualified"}},
  {U'🙋', { "person raising hand","fully-qualified"}},
  {U'🔙', { "BACK arrow","fully-qualified"}},
  {U'↪', { "left arrow curving right","unqualified"}},
  {U'🔗', { "link","fully-qualified"}},
  {U'♉', { "Taurus","fully-qualified"}},
  {U'🚖', { "oncoming taxi","fully-qualified"}},
  {U'🗒', { "spiral notepad","unqualified"}},
  {U'😜', { "winking face with tongue","fully-qualified"}},
  {U'⚧', { "transgender symbol","unqualified"}},
  {U'🐺', { "wolf","fully-qualified"}},
  {U'💈', { "barber pole","fully-qualified"}},
  {U'😴', { "sleeping face","fully-qualified"}},
  {U'🥢', { "chopsticks","fully-qualified"}},
  {U'🍜', { "steaming bowl","fully-qualified"}},
  {U'♒', { "Aquarius","fully-qualified"}},
  {U'🧳', { "luggage","fully-qualified"}},
  {U'🌰', { "chestnut","fully-qualified"}},
  {U'🚩', { "triangular flag","fully-qualified"}},
  {U'🥴', { "woozy face","fully-qualified"}},
  {U'🌪', { "tornado","unqualified"}},
  {U'🫶', { "heart hands","fully-qualified"}},
  {U'🍪', { "cookie","fully-qualified"}},
  {U'🌧', { "cloud with rain","unqualified"}},
  {U'🕘', { "nine o’clock","fully-qualified"}},
  {U'👤', { "bust in silhouette","fully-qualified"}},
  {U'🌘', { "waning crescent moon","fully-qualified"}},
  {U'🦐', { "shrimp","fully-qualified"}},
  {U'🐕', { "dog","fully-qualified"}},
  {U'➕', { "plus","fully-qualified"}},
  {U'🚨', { "police car light","fully-qualified"}},
  {U'🦘', { "kangaroo","fully-qualified"}},
  {U'🍒', { "cherries","fully-qualified"}},
  {U'🥳', { "partying face","fully-qualified"}},
  {U'🦮', { "guide dog","fully-qualified"}},
  {U'💊', { "pill","fully-qualified"}},
  {U'📁', { "file folder","fully-qualified"}},
  {U'🔢', { "input numbers","fully-qualified"}},
  {U'🍓', { "strawberry","fully-qualified"}},
  {U'🈹', { "Japanese “discount” button","fully-qualified"}},
  {U'🕝', { "two-thirty","fully-qualified"}},
  {U'🆒', { "COOL button","fully-qualified"}},
  {U'🛍', { "shopping bags","unqualified"}},
  {U'🐌', { "snail","fully-qualified"}},
  {U'🐔', { "chicken","fully-qualified"}},
  {U'🚔', { "oncoming police car","fully-qualified"}},
  {U'🎮', { "video game","fully-qualified"}},
  {U'🎷', { "saxophone","fully-qualified"}},
  {U'📞', { "telephone receiver","fully-qualified"}},
  {U'🛵', { "motor scooter","fully-qualified"}},
  {U'🥮', { "moon cake","fully-qualified"}},
  {U'✈', { "airplane","unqualified"}},
  {U'↙', { "down-left arrow","unqualified"}},
  {U'📕', { "closed book","fully-qualified"}},
  {U'🦏', { "rhinoceros","fully-qualified"}},
  {U'❔', { "white question mark","fully-qualified"}},
  {U'🔅', { "dim button","fully-qualified"}},
  {U'⚽', { "soccer ball","fully-qualified"}},
  {U'🥠', { "fortune cookie","fully-qualified"}},
  {U'💖', { "sparkling heart","fully-qualified"}},
  {U'🤚', { "raised back of hand","fully-qualified"}},
  {U'🕣', { "eight-thirty","fully-qualified"}},
  {U'🤵', { "person in tuxedo","fully-qualified"}},
  {U'🧶', { "yarn","fully-qualified"}},
  {U'🫚', { "ginger root","fully-qualified"}},
  {U'🦚', { "peacock","fully-qualified"}},
  {U'☦', { "orthodox cross","unqualified"}},
  {U'🕊', { "dove","unqualified"}},
  {U'🈲', { "Japanese “prohibited” button","fully-qualified"}},
  {U'🔱', { "trident emblem","fully-qualified"}},
  {U'🌆', { "cityscape at dusk","fully-qualified"}},
  {U'📈', { "chart increasing","fully-qualified"}},
  {U'🏛', { "classical building","unqualified"}},
  {U'🫁', { "lungs","fully-qualified"}},
  {U'🫴', { "palm up hand","fully-qualified"}},
  {U'🈶', { "Japanese “not free of charge” button","fully-qualified"}},
  {U'🕜', { "one-thirty","fully-qualified"}},
  {U'🧟', { "zombie","fully-qualified"}},
  {U'⛺', { "tent","fully-qualified"}},
  {U'🕥', { "ten-thirty","fully-qualified"}},
  {U'🌚', { "new moon face","fully-qualified"}},
  {U'🤺', { "person fencing","fully-qualified"}},
  {U'🪿', { "goose","fully-qualified"}},
  {U'👅', { "tongue","fully-qualified"}},
  {U'🩶', { "grey heart","fully-qualified"}},
  {U'♐', { "Sagittarius","fully-qualified"}},
  {U'⏏', { "eject button","unqualified"}},
  {U'🪜', { "ladder","fully-qualified"}},
  {U'🥘', { "shallow pan of food","fully-qualified"}},
  {U'🦺', { "safety vest","fully-qualified"}},
  {U'🆑', { "CL button","fully-qualified"}},
  {U'🫙', { "jar","fully-qualified"}},
  {U'🌳', { "deciduous tree","fully-qualified"}},
  {U'🌶', { "hot pepper","unqualified"}},
  {U'🎞', { "film frames","unqualified"}},
  {U'🪛', { "screwdriver","fully-qualified"}},
  {U'🌍', { "globe showing Europe-Africa","fully-qualified"}},
  {U'📑', { "bookmark tabs","fully-qualified"}},
  {U'💺', { "seat","fully-qualified"}},
  {U'🟰', { "heavy equals sign","fully-qualified"}},
  {U'✍', { "writing hand","unqualified"}},
  {U'🎻', { "violin","fully-qualified"}},
  {U'🦦', { "otter","fully-qualified"}},
  {U'🫑', { "bell pepper","fully-qualified"}},
  {U'🌛', { "first quarter moon face","fully-qualified"}},
//  {U'6⃣', { "keycap: 6","unqualified"}},
  {U'⛏', { "pick","unqualified"}},
  {U'🦨', { "skunk","fully-qualified"}},
  {U'👑', { "crown","fully-qualified"}},
  {U'💮', { "white flower","fully-qualified"}},
  {U'↘', { "down-right arrow","unqualified"}},
  {U'📲', { "mobile phone with arrow","fully-qualified"}},
  {U'💠', { "diamond with a dot","fully-qualified"}},
  {U'🛰', { "satellite","unqualified"}},
  {U'🍼', { "baby bottle","fully-qualified"}},
  {U'Ⓜ', { "circled M","unqualified"}},
  {U'🎒', { "backpack","fully-qualified"}},
  {U'🥥', { "coconut","fully-qualified"}},
  {U'🪮', { "hair pick","fully-qualified"}},
  {U'🐛', { "bug","fully-qualified"}},
  {U'😭', { "loudly crying face","fully-qualified"}},
  {U'🍇', { "grapes","fully-qualified"}},
  {U'🧭', { "compass","fully-qualified"}},
  {U'➖', { "minus","fully-qualified"}},
  {U'🥋', { "martial arts uniform","fully-qualified"}},
  {U'🌝', { "full moon face","fully-qualified"}},
  {U'🪡', { "sewing needle","fully-qualified"}},
  {U'⚛', { "atom symbol","unqualified"}},
  {U'🪐', { "ringed planet","fully-qualified"}},
  {U'🗻', { "mount fuji","fully-qualified"}},
  {U'🚉', { "station","fully-qualified"}},
  {U'🎹', { "musical keyboard","fully-qualified"}},
  {U'🐾', { "paw prints","fully-qualified"}},
  {U'🔨', { "hammer","fully-qualified"}},
  {U'🪁', { "kite","fully-qualified"}},
  {U'💅', { "nail polish","fully-qualified"}},
  {U'🎲', { "game die","fully-qualified"}},
  {U'🥸', { "disguised face","fully-qualified"}},
  {U'☢', { "radioactive","unqualified"}},
  {U'🪞', { "mirror","fully-qualified"}},
  {U'🔷', { "large blue diamond","fully-qualified"}},
  {U'🫨', { "shaking face","fully-qualified"}},
  {U'📴', { "mobile phone off","fully-qualified"}},
  {U'🏺', { "amphora","fully-qualified"}},
  {U'☪', { "star and crescent","unqualified"}},
  {U'🕷', { "spider","unqualified"}},
  {U'⬛', { "black large square","fully-qualified"}},
  {U'🫗', { "pouring liquid","fully-qualified"}},
  {U'🩴', { "thong sandal","fully-qualified"}},
  {U'🫡', { "saluting face","fully-qualified"}},
  {U'💥', { "collision","fully-qualified"}},
  {U'🩺', { "stethoscope","fully-qualified"}},
  {U'💃', { "woman dancing","fully-qualified"}},
  {U'👿', { "angry face with horns","fully-qualified"}},
  {U'🏻', { "light skin tone","component"}},
  {U'〰', { "wavy dash","unqualified"}},
  {U'🤭', { "face with hand over mouth","fully-qualified"}},
  {U'🌩', { "cloud with lightning","unqualified"}},
  {U'👯', { "people with bunny ears","fully-qualified"}},
  {U'♎', { "Libra","fully-qualified"}},
  {U'❗', { "red exclamation mark","fully-qualified"}},
  {U'🍞', { "bread","fully-qualified"}},
  {U'🔮', { "crystal ball","fully-qualified"}},
  {U'🗡', { "dagger","unqualified"}},
  {U'🚴', { "person biking","fully-qualified"}},
  {U'⏰', { "alarm clock","fully-qualified"}},
  {U'☠', { "skull and crossbones","unqualified"}},
  {U'🔽', { "downwards button","fully-qualified"}},
  {U'💟', { "heart decoration","fully-qualified"}},
  {U'🕸', { "spider web","unqualified"}},
  {U'😕', { "confused face","fully-qualified"}},
  {U'🪟', { "window","fully-qualified"}},
  {U'🛒', { "shopping cart","fully-qualified"}},
  {U'💑', { "couple with heart","fully-qualified"}},
  {U'🪣', { "bucket","fully-qualified"}},
  {U'🛶', { "canoe","fully-qualified"}},
  {U'🦗', { "cricket","fully-qualified"}},
  {U'☕', { "hot beverage","fully-qualified"}},
  {U'🦍', { "gorilla","fully-qualified"}},
  {U'🟩', { "green square","fully-qualified"}},
  {U'😓', { "downcast face with sweat","fully-qualified"}},
  {U'🥝', { "kiwi fruit","fully-qualified"}},
  {U'🥾', { "hiking boot","fully-qualified"}},
  {U'⏮', { "last track button","unqualified"}},
  {U'⛩', { "shinto shrine","unqualified"}},
  {U'👺', { "goblin","fully-qualified"}},
  {U'📖', { "open book","fully-qualified"}},
  {U'🕺', { "man dancing","fully-qualified"}},
  {U'🖤', { "black heart","fully-qualified"}},
  {U'↕', { "up-down arrow","unqualified"}},
  {U'🥼', { "lab coat","fully-qualified"}},
  {U'📶', { "antenna bars","fully-qualified"}},
  {U'🙏', { "folded hands","fully-qualified"}},
  {U'🩻', { "x-ray","fully-qualified"}},
  {U'💒', { "wedding","fully-qualified"}},
  {U'🟥', { "red square","fully-qualified"}},
  {U'🎽', { "running shirt","fully-qualified"}},
  {U'🌡', { "thermometer","unqualified"}},
  {U'🍮', { "custard","fully-qualified"}},
  {U'🤙', { "call me hand","fully-qualified"}},
  {U'❄', { "snowflake","unqualified"}},
  {U'⭐', { "star","fully-qualified"}},
  {U'🈂', { "Japanese “service charge” button","unqualified"}},
  {U'🧏', { "deaf person","fully-qualified"}},
  {U'🔃', { "clockwise vertical arrows","fully-qualified"}},
  {U'🈴', { "Japanese “passing grade” button","fully-qualified"}},
  {U'🕚', { "eleven o’clock","fully-qualified"}},
  {U'🦾', { "mechanical arm","fully-qualified"}},
  {U'👊', { "oncoming fist","fully-qualified"}},
  {U'🤖', { "robot","fully-qualified"}},
  {U'🪳', { "cockroach","fully-qualified"}},
  {U'🛺', { "auto rickshaw","fully-qualified"}},
  {U'🏤', { "post office","fully-qualified"}},
  {U'🌲', { "evergreen tree","fully-qualified"}},
  {U'👍', { "thumbs up","fully-qualified"}},
  {U'▶', { "play button","unqualified"}},
  {U'🎥', { "movie camera","fully-qualified"}},
  {U'💍', { "ring","fully-qualified"}},
  {U'🥟', { "dumpling","fully-qualified"}},
  {U'🧰', { "toolbox","fully-qualified"}},
  {U'🤷', { "person shrugging","fully-qualified"}},
  {U'🫂', { "people hugging","fully-qualified"}},
  {U'🌷', { "tulip","fully-qualified"}},
  {U'🍥', { "fish cake with swirl","fully-qualified"}},
  {U'🀄', { "mahjong red dragon","fully-qualified"}},
  {U'💽', { "computer disk","fully-qualified"}},
  {U'🥪', { "sandwich","fully-qualified"}},
  {U'🆙', { "UP! button","fully-qualified"}},
  {U'♈', { "Aries","fully-qualified"}},
  {U'🛞', { "wheel","fully-qualified"}},
  {U'🌨', { "cloud with snow","unqualified"}},
  {U'🩼', { "crutch","fully-qualified"}},
  {U'😾', { "pouting cat","fully-qualified"}},
  {U'☃', { "snowman","unqualified"}},
  {U'🪕', { "banjo","fully-qualified"}},
//  {U'2⃣', { "keycap: 2","unqualified"}},
  {U'🚱', { "non-potable water","fully-qualified"}},
  {U'✴', { "eight-pointed star","unqualified"}},
  {U'🛻', { "pickup truck","fully-qualified"}},
  {U'🧲', { "magnet","fully-qualified"}},
  {U'🔩', { "nut and bolt","fully-qualified"}},
  {U'😝', { "squinting face with tongue","fully-qualified"}},
  {U'🍑', { "peach","fully-qualified"}},
  {U'📘', { "blue book","fully-qualified"}},
  {U'🚝', { "monorail","fully-qualified"}},
  {U'♨', { "hot springs","unqualified"}},
  {U'📬', { "open mailbox with raised flag","fully-qualified"}},
  {U'🦴', { "bone","fully-qualified"}},
  {U'🧻', { "roll of paper","fully-qualified"}},
  {U'🩵', { "light blue heart","fully-qualified"}},
  {U'🎅', { "Santa Claus","fully-qualified"}},
  {U'🏐', { "volleyball","fully-qualified"}},
  {U'😬', { "grimacing face","fully-qualified"}},
  {U'🪥', { "toothbrush","fully-qualified"}},
  {U'🫷', { "leftwards pushing hand","fully-qualified"}},
  {U'😇', { "smiling face with halo","fully-qualified"}},
  {U'😘', { "face blowing a kiss","fully-qualified"}},
  {U'🫖', { "teapot","fully-qualified"}},
  {U'😪', { "sleepy face","fully-qualified"}},
  {U'🌈', { "rainbow","fully-qualified"}},
  {U'🐖', { "pig","fully-qualified"}},
//  {U'4⃣', { "keycap: 4","unqualified"}},
  {U'✝', { "latin cross","unqualified"}},
  {U'🔆', { "bright button","fully-qualified"}},
  {U'🦽', { "manual wheelchair","fully-qualified"}},
  {U'📪', { "closed mailbox with lowered flag","fully-qualified"}},
  {U'🔼', { "upwards button","fully-qualified"}},
  {U'♑', { "Capricorn","fully-qualified"}},
  {U'🫎', { "moose","fully-qualified"}},
  {U'🤲', { "palms up together","fully-qualified"}},
  {U'🪶', { "feather","fully-qualified"}},
  {U'⛲', { "fountain","fully-qualified"}},
  {U'💎', { "gem stone","fully-qualified"}},
  {U'🦟', { "mosquito","fully-qualified"}},
  {U'❣', { "heart exclamation","unqualified"}},
  {U'🦡', { "badger","fully-qualified"}},
  {U'🌗', { "last quarter moon","fully-qualified"}},
  {U'🥀', { "wilted flower","fully-qualified"}},
  {U'🥣', { "bowl with spoon","fully-qualified"}},
  {U'⤵', { "right arrow curving down","unqualified"}},
  {U'🚫', { "prohibited","fully-qualified"}},
  {U'🤔', { "thinking face","fully-qualified"}},
  {U'🥜', { "peanuts","fully-qualified"}},
  {U'⁉', { "exclamation question mark","unqualified"}},
  {U'🏹', { "bow and arrow","fully-qualified"}},
  {U'🥨', { "pretzel","fully-qualified"}},
  {U'🫤', { "face with diagonal mouth","fully-qualified"}},
  {U'👄', { "mouth","fully-qualified"}},
  {U'🦱', { "curly hair","component"}},
  {U'🤏', { "pinching hand","fully-qualified"}},
  {U'🎶', { "musical notes","fully-qualified"}},
  {U'🪑', { "chair","fully-qualified"}},
  {U'🎧', { "headphone","fully-qualified"}},
  {U'😄', { "grinning face with smiling eyes","fully-qualified"}},
  {U'🤠', { "cowboy hat face","fully-qualified"}},
  {U'😳', { "flushed face","fully-qualified"}},
  {U'🐉', { "dragon","fully-qualified"}},
  {U'🧊', { "ice","fully-qualified"}},
  {U'🐝', { "honeybee","fully-qualified"}},
  {U'🕖', { "seven o’clock","fully-qualified"}},
  {U'🧑', { "person","fully-qualified"}},
  {U'🏩', { "love hotel","fully-qualified"}},
  {U'🏿', { "dark skin tone","component"}},
  {U'🔰', { "Japanese symbol for beginner","fully-qualified"}},
  {U'◻', { "white medium square","unqualified"}},
  {U'💼', { "briefcase","fully-qualified"}},
  {U'🌵', { "cactus","fully-qualified"}},
  {U'🐏', { "ram","fully-qualified"}},
  {U'📓', { "notebook","fully-qualified"}},
  {U'🔺', { "red triangle pointed up","fully-qualified"}},
  {U'🎦', { "cinema","fully-qualified"}},
  {U'🎗', { "reminder ribbon","unqualified"}},
  {U'🤕', { "face with head-bandage","fully-qualified"}},
  {U'🧝', { "elf","fully-qualified"}},
  {U'🫸', { "rightwards pushing hand","fully-qualified"}},
  {U'⛴', { "ferry","unqualified"}},
  {U'🏎', { "racing car","unqualified"}},
  {U'🛃', { "customs","fully-qualified"}},
  {U'⛅', { "sun behind cloud","fully-qualified"}},
  {U'🤗', { "smiling face with open hands","fully-qualified"}},
  {U'🦇', { "bat","fully-qualified"}},
  {U'⛳', { "flag in hole","fully-qualified"}},
  {U'🌕', { "full moon","fully-qualified"}},
  {U'💧', { "droplet","fully-qualified"}},
  {U'🚒', { "fire engine","fully-qualified"}},
  {U'❎', { "cross mark button","fully-qualified"}},
  {U'🔑', { "key","fully-qualified"}},
  {U'🦈', { "shark","fully-qualified"}},
  {U'🦒', { "giraffe","fully-qualified"}},
  {U'☂', { "umbrella","unqualified"}},
  {U'👃', { "nose","fully-qualified"}},
  {U'🌔', { "waxing gibbous moon","fully-qualified"}},
  {U'💗', { "growing heart","fully-qualified"}},
  {U'🎍', { "pine decoration","fully-qualified"}},
  {U'📡', { "satellite antenna","fully-qualified"}},
  {U'🥞', { "pancakes","fully-qualified"}},
  {U'👒', { "woman’s hat","fully-qualified"}},
  {U'🐇', { "rabbit","fully-qualified"}},
  {U'💐', { "bouquet","fully-qualified"}},
  {U'😊', { "smiling face with smiling eyes","fully-qualified"}},
  {U'😻', { "smiling cat with heart-eyes","fully-qualified"}},
  {U'🦂', { "scorpion","fully-qualified"}},
  {U'☎', { "telephone","unqualified"}},
  {U'📚', { "books","fully-qualified"}},
  {U'✅', { "check mark button","fully-qualified"}},
  {U'🧡', { "orange heart","fully-qualified"}},
  {U'🔦', { "flashlight","fully-qualified"}},
  {U'🍦', { "soft ice cream","fully-qualified"}},
  {U'🍷', { "wine glass","fully-qualified"}},
  {U'⚔', { "crossed swords","unqualified"}},
  {U'🍲', { "pot of food","fully-qualified"}},
  {U'🥛', { "glass of milk","fully-qualified"}},
  {U'♏', { "Scorpio","fully-qualified"}},
  {U'🔤', { "input latin letters","fully-qualified"}},
  {U'👋', { "waving hand","fully-qualified"}},
  {U'📵', { "no mobile phones","fully-qualified"}},
  {U'🎑', { "moon viewing ceremony","fully-qualified"}},
  {U'🧼', { "soap","fully-qualified"}},
  {U'📿', { "prayer beads","fully-qualified"}},
  {U'🟪', { "purple square","fully-qualified"}},
  {U'🐒', { "monkey","fully-qualified"}},
  {U'◀', { "reverse button","unqualified"}},
  {U'💙', { "blue heart","fully-qualified"}},
  {U'💴', { "yen banknote","fully-qualified"}},
  {U'⚠', { "warning","unqualified"}},
  {U'📣', { "megaphone","fully-qualified"}},
  {U'🐵', { "monkey face","fully-qualified"}},
  {U'🩸', { "drop of blood","fully-qualified"}},
  {U'🎢', { "roller coaster","fully-qualified"}},
  {U'⛸', { "ice skate","unqualified"}},
  {U'☺', { "smiling face","unqualified"}},
  {U'🏷', { "label","unqualified"}},
  {U'🫛', { "pea pod","fully-qualified"}},
  {U'🌏', { "globe showing Asia-Australia","fully-qualified"}},
  {U'🎄', { "Christmas tree","fully-qualified"}},
  {U'🤾', { "person playing handball","fully-qualified"}},
  {U'🎂', { "birthday cake","fully-qualified"}},
  {U'🎈', { "balloon","fully-qualified"}},
  {U'🚁', { "helicopter","fully-qualified"}},
  {U'🌇', { "sunset","fully-qualified"}},
  {U'🐑', { "ewe","fully-qualified"}},
  {U'🚞', { "mountain railway","fully-qualified"}},
  {U'🔹', { "small blue diamond","fully-qualified"}},
  {U'🛁', { "bathtub","fully-qualified"}},
  {U'🆓', { "FREE button","fully-qualified"}},
  {U'♊', { "Gemini","fully-qualified"}},
  {U'🫐', { "blueberries","fully-qualified"}},
  {U'☮', { "peace symbol","unqualified"}},
  {U'💩', { "pile of poo","fully-qualified"}},
  {U'🪻', { "hyacinth","fully-qualified"}},
  {U'🏋', { "person lifting weights","unqualified"}},
  {U'🦝', { "raccoon","fully-qualified"}},
  {U'🧴', { "lotion bottle","fully-qualified"}},
  {U'🚍', { "oncoming bus","fully-qualified"}},
  {U'🐈', { "cat","fully-qualified"}},
  {U'📗', { "green book","fully-qualified"}},
  {U'🛼', { "roller skate","fully-qualified"}},
  {U'🚅', { "bullet train","fully-qualified"}},
  {U'💁', { "person tipping hand","fully-qualified"}},
  {U'🚚', { "delivery truck","fully-qualified"}},
  {U'👪', { "family","fully-qualified"}},
  {U'🌸', { "cherry blossom","fully-qualified"}},
  {U'⬆', { "up arrow","unqualified"}},
  {U'🈷', { "Japanese “monthly amount” button","unqualified"}},
  {U'🤌', { "pinched fingers","fully-qualified"}},
  {U'🎆', { "fireworks","fully-qualified"}},
  {U'🎸', { "guitar","fully-qualified"}},
  {U'🕗', { "eight o’clock","fully-qualified"}},
  {U'🌥', { "sun behind large cloud","unqualified"}},
  {U'🏓', { "ping pong","fully-qualified"}},
  {U'🚰', { "potable water","fully-qualified"}},
  {U'☑', { "check box with check","unqualified"}},
  {U'⛰', { "mountain","unqualified"}},
  {U'🍳', { "cooking","fully-qualified"}},
  {U'🛎', { "bellhop bell","unqualified"}},
  {U'🥫', { "canned food","fully-qualified"}},
  {U'⬅', { "left arrow","unqualified"}},
  {U'🏃', { "person running","fully-qualified"}},
  {U'🖇', { "linked paperclips","unqualified"}},
  {U'♿', { "wheelchair symbol","fully-qualified"}},
  {U'👸', { "princess","fully-qualified"}},
  {U'↩', { "right arrow curving left","unqualified"}},
  {U'🤝', { "handshake","fully-qualified"}},
  {U'🍋', { "lemon","fully-qualified"}},
  {U'🏫', { "school","fully-qualified"}},
  {U'🕛', { "twelve o’clock","fully-qualified"}},
  {U'🚏', { "bus stop","fully-qualified"}},
  {U'🌙', { "crescent moon","fully-qualified"}},
  {U'🧂', { "salt","fully-qualified"}},
  {U'😫', { "tired face","fully-qualified"}},
  {U'🧎', { "person kneeling","fully-qualified"}},
  {U'🍀', { "four leaf clover","fully-qualified"}},
  {U'🍤', { "fried shrimp","fully-qualified"}},
  {U'🌭', { "hot dog","fully-qualified"}},
  {U'🐘', { "elephant","fully-qualified"}},
  {U'🧱', { "brick","fully-qualified"}},
  {U'👻', { "ghost","fully-qualified"}},
  {U'🍴', { "fork and knife","fully-qualified"}},
  {U'👙', { "bikini","fully-qualified"}},
  {U'🪀', { "yo-yo","fully-qualified"}},
  {U'🛫', { "airplane departure","fully-qualified"}},
  {U'🛌', { "person in bed","fully-qualified"}},
  {U'🥈', { "2nd place medal","fully-qualified"}},
  {U'🪚', { "carpentry saw","fully-qualified"}},
  {U'🧠', { "brain","fully-qualified"}},
  {U'🐥', { "front-facing baby chick","fully-qualified"}},
  {U'🗿', { "moai","fully-qualified"}},
  {U'🍅', { "tomato","fully-qualified"}},
  {U'🎏', { "carp streamer","fully-qualified"}},
  {U'🐷', { "pig face","fully-qualified"}},
  {U'😿', { "crying cat","fully-qualified"}},
  {U'🅱', { "B button (blood type)","unqualified"}},
  {U'🥡', { "takeout box","fully-qualified"}},
  {U'🫲', { "leftwards hand","fully-qualified"}},
  {U'⚙', { "gear","unqualified"}},
  {U'🍣', { "sushi","fully-qualified"}},
  {U'🪵', { "wood","fully-qualified"}},
  {U'🥄', { "spoon","fully-qualified"}},
  {U'🌮', { "taco","fully-qualified"}},
  {U'🏇', { "horse racing","fully-qualified"}},
  {U'🕔', { "five o’clock","fully-qualified"}},
  {U'🈁', { "Japanese “here” button","fully-qualified"}},
  {U'🌽', { "ear of corn","fully-qualified"}},
  {U'🌓', { "first quarter moon","fully-qualified"}},
  {U'🔵', { "blue circle","fully-qualified"}},
  {U'🦅', { "eagle","fully-qualified"}},
  {U'⏩', { "fast-forward button","fully-qualified"}},
  {U'👔', { "necktie","fully-qualified"}},
  {U'🧵', { "thread","fully-qualified"}},
  {U'🎾', { "tennis","fully-qualified"}},
  {U'🌌', { "milky way","fully-qualified"}},
  {U'🚺', { "women’s room","fully-qualified"}},
  {U'📀', { "dvd","fully-qualified"}},
  {U'👽', { "alien","fully-qualified"}},
  {U'🗽', { "Statue of Liberty","fully-qualified"}},
  {U'🤤', { "drooling face","fully-qualified"}},
  {U'🔍', { "magnifying glass tilted left","fully-qualified"}},
  {U'✋', { "raised hand","fully-qualified"}},
  {U'🈸', { "Japanese “application” button","fully-qualified"}},
  {U'🏯', { "Japanese castle","fully-qualified"}},
  {U'🚣', { "person rowing boat","fully-qualified"}},
  {U'🌄', { "sunrise over mountains","fully-qualified"}},
  {U'🌾', { "sheaf of rice","fully-qualified"}},
  {U'🏸', { "badminton","fully-qualified"}},
  {U'🐡', { "blowfish","fully-qualified"}},
  {U'🦼', { "motorized wheelchair","fully-qualified"}},
  {U'🕐', { "one o’clock","fully-qualified"}},
  {U'😏', { "smirking face","fully-qualified"}},
  {U'🤢', { "nauseated face","fully-qualified"}},
  {U'🕒', { "three o’clock","fully-qualified"}},
  {U'🥔', { "potato","fully-qualified"}},
  {U'🥉', { "3rd place medal","fully-qualified"}},
  {U'🪧', { "placard","fully-qualified"}},
  {U'😷', { "face with medical mask","fully-qualified"}},
  {U'🌎', { "globe showing Americas","fully-qualified"}},
  {U'🥃', { "tumbler glass","fully-qualified"}},
  {U'⚾', { "baseball","fully-qualified"}},
  {U'🔕', { "bell with slash","fully-qualified"}},
  {U'🚽', { "toilet","fully-qualified"}},
  {U'🤡', { "clown face","fully-qualified"}},
  {U'🕧', { "twelve-thirty","fully-qualified"}},
  {U'🚶', { "person walking","fully-qualified"}},
  {U'🧹', { "broom","fully-qualified"}},
  {U'▪', { "black small square","unqualified"}},
  {U'🦌', { "deer","fully-qualified"}},
  {U'😨', { "fearful face","fully-qualified"}},
  {U'ℹ', { "information","unqualified"}},
  {U'🏂', { "snowboarder","fully-qualified"}},
  {U'😒', { "unamused face","fully-qualified"}},
  {U'🏞', { "national park","unqualified"}},
  {U'🕵', { "detective","unqualified"}},
  {U'✉', { "envelope","unqualified"}},
  {U'🌹', { "rose","fully-qualified"}},
  {U'🚬', { "cigarette","fully-qualified"}},
  {U'🌺', { "hibiscus","fully-qualified"}},
  {U'🤞', { "crossed fingers","fully-qualified"}},
//  {U'0⃣', { "keycap: 0","unqualified"}},
  {U'😖', { "confounded face","fully-qualified"}},
  {U'🤍', { "white heart","fully-qualified"}},
  {U'🧄', { "garlic","fully-qualified"}},
  {U'⏸', { "pause button","unqualified"}},
  {U'⏬', { "fast down button","fully-qualified"}},
  {U'🖨', { "printer","unqualified"}},
  {U'😶', { "face without mouth","fully-qualified"}},
  {U'🪈', { "flute","fully-qualified"}},
  {U'👁', { "eye","unqualified"}},
  {U'🙌', { "raising hands","fully-qualified"}},
};
}
